colorscheme gruvbox-dark

set-option global tabstop 4
set-option global indentwidth 0
set-option global scrolloff 1,3

set-option global ui_options terminal_assistant=cat

add-highlighter global/ number-lines -hlcursor
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent


hook global WinSetOption filetype=c %{
	clang-enable-diagnostics
}
hook global WinSetOption filetype=cpp %{
	clang-enable-diagnostics
}

set global grepcmd 'rg -n'


map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'

map global user '#' %{: comment-line<ret>} -docstring 'comment lines'

map global user c 'x_c' -docstring 'change line'

map global user y '<a-|> wl-copy -n 2> /dev/null <ret>' -docstring 'yank selection into the clipboard'
map global user p '<a-!> wl-paste -n <ret>' -docstring 'paste from clipboard'

map global goto e '<esc>gevv' -docstring 'buffer end'

map global user i '<a-i>' -docstring 'select inner surrounding object'
map global user a '<a-a>' -docstring 'select surrounding object'
# TODO why does this not work with empyt lines inbetween????
map global user s '<a-s>' -docstring 'split selection by lines'

map global normal <c-p> ':clang-parse<ret>' -docstring 'clang-parse current buffer'
map global normal <c-l> ':clang-diagnostics-next<ret>'


define-command 'reflow' 'execute-keys "| fmt -w 79<ret>"'

